services: 
  db:
    image: postgres
    restart: always
    env_file:
      - path: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    depends_on:
      - adminer
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
